### ISSUE TITLE
Unclear documentation on DB migrations for SQLite

### ISSUE THREAD

**Issue by theseanything** [vapor/docs#314]
I tried implementing the `prepare` method for a custom migration for SQLite. However found the documentation really difficult to follow and ultimately didn't work. I was following the steps outlined under the `prepare` section in [Fluent -> Migrations ](https://docs.vapor.codes/3.0/fluent/migrations/) for Vapor 3.0

The current example for `prepare` uses `MySQLConnection`, which I just assumed I can substitute out for SQLiteConnection. However doing so causes a `'SQLiteConnection' has no member 'create'` build error. 

Thought it maybe a SQLite specific issue, however looking under the [Fluent SQLite section](https://docs.vapor.codes/3.0/sqlite/fluent/) just redirects to the more general [Fluent -> Migration section](https://docs.vapor.codes/3.0/fluent/migrations/).

Would be great to have working documentation on this process! Not sure if this a SQLite specific issue or how this documentation is generalised to all Fluent providers...

I am using Vapor 3.0.0 and FluentSQLite 3.0.0-rc2.2

**Comment by tanner0101** [comment]
Did you have `import FluentSQLite` added? The docs should be fairly similar between the two so that is surprising. Either way, yes it's ultimately the goal once FluentSQLite is released for it to have its own docs wherever possible.

**Comment by theseanything** [comment]
Yup had `import FluentSQLite`. So I think issue is in the documentation and its not actually specific to SQLite.

The documentation currently has:

```swift
    static func prepare(on connection: MySQLConnection) -> Future<Void> {
        return connection.create(self) { builder in
            try builder.field(for: \.id)
            try builder.field(for: \.name)
            try builder.field(for: \.age)
        }
    }
```
but I think should be this (and it works)....

```swift
    static func prepare(on connection: MySQLConnection) -> Future<Void> {
        return Database.create(self, on: connection) { builder in
            try builder.field(for: \.id)
            try builder.field(for: \.name)
            try builder.field(for: \.age)
        }
    }
```

where MySQLConnection can be substituted for SQLiteConnection

**Comment by 0xTim** [comment]
@theseanything the docs are actually massively out of date. You can just do `extension MyModel: Migration {}` with nothing else
