### ISSUE TITLE
Routing issue: vapor docs url without trailing '/' times out.

### ISSUE THREAD

**Issue by marc-medley** [vapor/docs#319]
The vapor doc URLs `https://docs.vapor.codes/2.0/` and `https://docs.vapor.codes/3.0/` responds OK.

However, [`https://docs.vapor.codes/2.0`](https://docs.vapor.codes/2.0) and [`https://docs.vapor.codes/3.0`](https://docs.vapor.codes/3.0) timeout.

After the connections times out, then the URLs that timed out show as `https://docs.vapor.codes:8080/2.0/` and `https://docs.vapor.codes:8080/3.0/` in the browser navigaton bar.

So, my exiting vapor doc bookmarks (that used to work) needed to be updated with the appended `/`.

Relocated from [https://github.com/vapor/website/issues/17](https://github.com/vapor/website/issues/17)

**Comment by 0xTim** [comment]
This seems to be fixed now
