### ISSUE TITLE
Model willCreate example returns wrong data type

### ISSUE THREAD

**Issue by EricWVGG** [vapor/docs#326]
/vapor/documentation/blob/master/3.0/docs/fluent/models.md (line 170)

In the code description for a rhetorical model called User, the example indicates that the return should be of type ```Future<Self>```. It should be ```Future<User>```.
```
func willUpdate(on connection: Database.Connection) throws -> Future<Self> {
```

I'm not sure whether it's self-explanatory or not that, on the same line, "Database.Connection" should be "SQLiteConnection" or "MySQLConnection" or whatever.

**Comment by 0xTim** [comment]
`Self` should work, since it's in the scope of `User` right? I'm closing this due to age, but feel free to reopen if you want!
