### ISSUE TITLE
Document using CORS middleware

### ISSUE THREAD

**Issue by joscdk** [vapor/docs#349]
Write documentation on how to use the CORS middleware.

Snippet from Steven on Discord:

```swift
// CORS
    let corsConfig = CORSMiddleware.Configuration(allowedOrigin: .all, allowedMethods: [.POST, .GET], allowedHeaders: [.contentType, .accept])
    let coresMiddleware = CORSMiddleware(configuration: corsConfig)
    middlewares.use(coresMiddleware)
```

**Comment by rafiki270** [comment]
Mainly the info on where the CORS needs to be in terms of affecting other middlewares like error handling etc!

**Comment by 0xTim** [comment]
This is now done - https://docs.vapor.codes/4.0/middleware/#cors-middleware
