### ISSUE TITLE
Add warning about selecting the correct command line tools

### ISSUE THREAD

**Issue by vzsg** [vapor/docs#355]
If the active command line tools is set to a "Command Line Tools for Xcode" installation instead of a valid Xcode path, building the project or generating an xcodeproj fails with cryptic errors, for example:

``` Generating Xcode Project [Failed]
error: terminated(72): xcrun --sdk macosx --find xctest output:
    


Error: Could not generate Xcode project: error: terminated(72): xcrun --sdk macosx --find xctest output:
```

Unfortunately, Homebrew's current install script seems to install and activate the Command Line Tools package even if there's a real Xcode installed on the system, so it's likely that new users will regularly run into this issue.

---

We should add a note to the macOS install guide to select the correct command line tools either via `sudo xcode-select -s`, or Xcode's Preferences-Locations.

**Comment by gwynne** [comment]
This is no longer relevant with current versions of Swift and Xcode.
