### ISSUE TITLE
Setup Info: Vapor 3 + Swift 4.2 + Ubuntu 18.04

### ISSUE THREAD

**Issue by marc-medley** [vapor/docs#359]
Is there any "Install on Ubuntu" documentation/information that can be provided for a setup of Vapor 3 + Swift 4.2 + Unbuntu 18.04 configuration?

… since Swift.org (Apple) is now providing **Swift 4.2** releases for **Ubunutu 18.04**:

* [Swift 4.2 Convergence Snapshots](https://swift.org/download/#swift-42-convergence-snapshots)
* [Swift 4.2 Development](https://swift.org/download/#swift-42-development)
* [Trunk Development (master)](https://swift.org/download/#trunk-development-master)

**Comment by joscdk** [comment]
@marc-medley you can always download swift manually, and use it. In theory Vapor 3 should work on Swift 4.2, but i havn't tried it out personally.

Our APT will be updated after Swift 4.2 hits release.

**Comment by vzsg** [comment]
Note that even though there are _snapshots_ for Swift 4.2 on Ubuntu 18.04 (releases will probably come with Xcode 10), Vapor does not support OpenSSL 1.1 – the new default on 18.04 – on the source level, so it is not compatible with Ubuntu 18.04 in the end.

**Comment by joscdk** [comment]
Good point @vzsg :)

**Comment by marc-medley** [comment]
Thanks for the info that Vapor/Crypto does not support OpenSSL 1.1 (as provided via Ubuntu 18.04) at this time.  I'll wait until some undetermined future date to try a Vapor 3 + Swift 4.2 + Unbuntu 18.04 source build.

That said, it would be helpful if the Vapor/Documentation carried forward the [Vapor 2.0 "Getting started > Manual"](https://docs.vapor.codes/2.0/getting-started/manual/) docs as well as some info for early-adopter/developer configurations. 

In particular, it would be helpful to have some basic guidance for a what is "workable leading edge" (e.g. maybe Vapor branch xyz + Swift 4.2 Convergence snapshot + Ubuntu 16.04) and what is "not yet" (e.g. Vapor 3 + Swift 4.2 + Unbuntu 18.04) pending resolution of some known issue(s).

**Comment by joscdk** [comment]
@andy1247008998 yeah it's on the todo, however there are a couple of urgent tasks to get done right now :) .. It will be done asap.

We are also currently looking into ways to make APT easier to keep up to date in the future, naming and a couple of other things :)

**Comment by marc-medley** [comment]
At this time, are there any known blocking issues for the Vapor 3 + Swift 4.2 + Unbuntu 18.04 combination? Or, perhaps any preliminary test findings?

**Comment by vzsg** [comment]
The combination should work now, as the major hurdle was eliminated (vapor/crypto supports both 1.0.2 and 1.1.0 of OpenSSL). I don't know the status of the Vapor APT repo, nor the toolbox on the other hand, but manually installing the Swift toolchain from swift.org and using `swift package` commands should work fine.

**Comment by 0xTim** [comment]
Closing as all these issues should now be resolved and there are docs for deploying onto DO on Ubuntu
