### ISSUE TITLE
[Styleguide] Swift 4.2 fails with API Controllers folder

### ISSUE THREAD

**Issue by gperdomor** [vapor/docs#369]
Swift 4.2 fails to compile in Linux when you have a folder `API Controllers`

**Comment by mcdappdev** [comment]
@gperdomor This is most likely due to a bug that has problems with spaces in folder names. Do you want to make a PR for the docs?

**Comment by gperdomor** [comment]
Yes, I think that too, but the decision is: `APIControllers` or just `API` like before?

**Comment by mcdappdev** [comment]
I would say just `API` since it's already under the `Controllers` umbrella. We should probably also make it just `Views` then as well.

**Comment by gperdomor** [comment]
ready https://github.com/vapor/documentation/pull/370
