### ISSUE TITLE
How to Handle Hanging Futures

### ISSUE THREAD

**Issue by calebkleveter** [vapor/docs#381]
There should be a section in the `Async` docs that covers hanging futures. Most people try to use `_ =`, but that can cause memory leaks.

**Comment by mcdappdev** [comment]
Agreed, maybe something can be built on from this: https://docs.vapor.codes/3.0/async/overview/#blocking

**Comment by grundoon** [comment]
So, I'm pretty guilty of that in (the reasonably safe case of) unit tests.
Not to force use of your all's time prematurely, but what *is* the generally correct handling of a return that you just don't care about in production async – is simply `let _ =` good enough?

**Comment by mcdappdev** [comment]
I think the general answer is that it depends. If that future is using a connection to a database then it’s definitely not safe. I’m not 100% positive of the recommended route but I’m pretty sure DispatchQueue is necessary. The other thing would be to dispatch it as a job to a queueing system (the jobs package isn’t quite ready yet but hopefully soon!)

**Comment by 0xTim** [comment]
You can also use NIO's `scheduleTask` and schedule it for immediately

**Comment by mcdappdev** [comment]
Oh yeah, that’s a great idea

**Comment by 0xTim** [comment]
Closing this as dangling futures aren't an issue in Vapor 4 and async/await also supersedes this
