### ISSUE TITLE
Leaf: document when left closing bracket escaping is needed. 

### ISSUE THREAD

**Issue by marc-medley** [vapor/docs#398]
It would be really helpful if the Leaf 3 document expressly stated when escaping the left closing bracket(s) is needed. 

Affected Page: https://docs.vapor.codes/3.0/leaf/overview/

_Possible page addition:_

Currently Leaf does not directly handle body content which contains a closing left bracket `}`. In these situations, the content (not the Leaf syntax) needs to have all the closing left bracket escaped `\}`.

For example, the following mathematical expressions escape the left closing bracket while the leaving the Leaf syntax unescaped. 

``` html
#set("body") {
<p>Two equations: \(A^T_S = B\) and \(\sqrt{ab\}\).</p>
    <p>\[A^T_S = B\]  </p>
<p>\[\sqrt{ab\}\]  </p>
}
```

![EscapedLeftOutput](https://user-images.githubusercontent.com/15098151/54094815-c1de3f00-4360-11e9-8ce5-6499ba46b8b2.png)

---

Related issue: https://github.com/vapor/leaf/issues/133

**Comment by 0xTim** [comment]
This should be fixed in Leaf 4 with the migration to `#if(something):#endif`
