### ISSUE TITLE
Docs shouldn't ever suggest using `wait()`

### ISSUE THREAD

**Issue by twof** [vapor/docs#399]
https://github.com/vapor/vapor/issues/1669#issuecomment-474404485

**Comment by tanner0101** [comment]
Yeah that's a good point. Some of the docs were written in the context of being in a `main.swift` file. But we should assume that people will be copy pasting that stuff into route closures.

**Comment by zachwick** [comment]
It appears that in the Vapor 4 docs, this footgun has been removed, and the examples at https://docs.vapor.codes/4.0/client/ use `map()` .

Checking through other places in the Vapor 4 docs using `git grep "wait()"` only yields results where either using `wait()` is appropriate, or explicit callouts in the documentation about when using `wait()` is not appropriate.

**Comment by 0xTim** [comment]
Will close the issue then, thanks!
