### ISSUE TITLE
Leaf section doesn't contain instructions for all tags

### ISSUE THREAD

**Issue by alexsteinerde** [vapor/docs#408]
The Leaf section describes some tags that are available in the library. But the raw Tag that is shipped in code is not described. 
To use this Tag it is additionally required to add the tag yourself to the custom tags during configuration.
Has it any purpose to leave this section outdated and will there be some big changes in Vapor 3 were the documentation will be rewritten entirely?

**Comment by tanner0101** [comment]
> To use this Tag it is additionally required to add the tag yourself to the custom tags during configuration.

The raw tag is available as `#get`: https://github.com/vapor/template-kit/blob/master/Sources/TemplateKit/Tag/TagRenderer.swift#L25

> Has it any purpose to leave this section outdated and will there be some big changes in Vapor 3 were the documentation will be rewritten entirely?

Yes, the docs will be updated for changes to Leaf in Vapor 4. `#get` will still be available in the next version, so we should definitely add documentation.

**Comment by alexsteinerde** [comment]
Ok, I found the exact same question in the comment section at the bottom of the documentation. They are very helpful too.

> Yes, the docs will be updated for changes to Leaf in Vapor 4. #get will still be available in the next version, so we should definitely add documentation.

After knowing that `#get` is an alias for `#raw` I could read this between the lines. But an explicit sentence about inserting raw HTML that is generated from Swift code into the template would be helpful. 
If you need any help expanding the documentation just let me know.

**Comment by 0xTim** [comment]
I think all tags are now documented for Leaf 4
