### ISSUE TITLE
Clarify that createdAt, updatedAt, deletedAt must all be Date?

### ISSUE THREAD

**Issue by Jerry-Carter** [vapor/docs#417]
The question was asked in #fluent on Discord: "Does the created_at property have to be optional Date? I guess yes for the same reason id is".

This should be clarified.  I'll try to so so shortly.

**Comment by tanner0101** [comment]
@Jerry-Carter yes, they must be `Date?`. That is how `TimestampKey` is defined here: https://api.vapor.codes/fluent/3.2.0/Fluent/Protocols/Model.html#/s:6Fluent5ModelP12createdAtKeys08WritableE4PathCyx10Foundation4DateVSgGSgvpZ

**Comment by 0xTim** [comment]
This is clarified in https://docs.vapor.codes/4.0/fluent/model/#timestamp
