### ISSUE TITLE
Write more info to CORS

### ISSUE THREAD

**Issue by j4nos** [vapor/docs#422]
Codes are applied specified in docs, but BE still refuse FE request running on other domain, what am I missing?

I have only simple routes. Cleared cache in browser.

<img width="669" alt="Képernyőfotó 2019-12-02 - 23 19 36" src="https://user-images.githubusercontent.com/11924475/70002872-a3108000-1561-11ea-91ab-3522a3c44f53.png">

I even added this line to the router:

```
req.response().http.headers.add(name: "Access-Control-Allow-Origin", value:"*")
```

I see some errors in browser, and no response at all from BE:

<img width="1242" alt="Képernyőfotó 2019-12-02 - 23 33 47" src="https://user-images.githubusercontent.com/11924475/70002893-b3285f80-1561-11ea-99c0-c2fd3e35291c.png">
<img width="1440" alt="Képernyőfotó 2019-12-02 - 23 32 55" src="https://user-images.githubusercontent.com/11924475/70002895-b3c0f600-1561-11ea-8554-c5c96e7661b0.png">

**Comment by 0xTim** [comment]
@j4nos  closing this as Discord would be a better place to discuss the best implementation of CORS for your use case
