### ISSUE TITLE
Add notes on Property Wrappers to the Vapor 4 docs

### ISSUE THREAD

**Issue by daSkier** [vapor/docs#447]
I don't have a clear understanding of the usage of `$` with with Fluent's property wrappers. It'd be nice if an explanation of this were added to both the "Fluent - Overview" and "Upgrading - Fluent" sections of the docs. 

I know we're early in the docs process, but I wanted to point it out. If someone can explain it quickly or point me in the right direction to gain an understanding I'd be happy to attempt to write something up. 

Thanks!

**Comment by 0xTim** [comment]
@daSkier I'm going to close this as this is more of a Swift thing than a Vapor thing. The best place to look is the Swift docs here https://docs.swift.org/swift-book/LanguageGuide/Properties.html
