### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by tanner0101** [vapor/docs#448]
Search engines should not return results for old docs versions.

**Comment by BennyDeBock** [comment]
@0xTim Can this be closed?

With the split of the legacy docs and the Vapor 4 documentation I always seem to find the up-to-date vapor docs first.

![image](https://user-images.githubusercontent.com/74614235/188850804-e4710ca2-a050-44ee-98b1-a4af98b44df2.png)

**Comment by 0xTim** [comment]
Yes we can close this since we've reworked the docs now
