### ISSUE TITLE
Add Docker deploy documentation to Vapor 4 docs

### ISSUE THREAD

**Issue by daSkier** [vapor/docs#461]
I know @gwynne has been working on updated Vapor Docker images. I would be nice to include some documentation of their use in the Deploy section of the Vapor 4 docs. 

For reference she did provide the following basic Docker file:
```Dockerfile
FROM vapor/swift:5.2 as builder
WORKDIR /build
COPY . .
RUN swift build -v --enable-test-discovery -c release -Xswiftc -g

FROM vapor/ubuntu:18.04
WORKDIR /run
ARG env
ENV env ${env:-development}
COPY --from=builder /build/.build/release /run
ENTRYPOINT ["./Run"]
CMD ["serve", "--env", "$env", "--hostname", "0.0.0.0", "--port", "8080"] 
```

**Comment by tanner0101** [comment]
`vapor new` ships with a Docker template and docker-compose file:

- https://github.com/vapor/template/blob/master/Dockerfile
- https://github.com/vapor/template/blob/master/docker-compose.yml

I think the guide docs should show people how to use these for both local development (testing on linux, spinning up dbs, etc) and deployment.

**Comment by daSkier** [comment]
@tanner0101 One of the things I found confusing when reading those template files were the mustache variables. I'm not familiar with the system, I just saw somebody explain the `{{/fluent}}{{#fluent.db.is_postgres}}` type stuff that way. 

It may be helpful to at least outline to users what is happening there even if it doesn't explain how to use mustache for their own use case.

**Comment by mattpolzin** [comment]
@daSkier the template is used by the `vapor new` command to produce a new project with a dockerfile in it. The produced dockerfile will no longer have any templating tags. That said, I think a full example of a dockerfile without templating tags would be a beneficial addition to these docs for the purposes of walking through how the dockerfile works. I might throw some time at these docs this weekend finally.
