### ISSUE TITLE
Docs for .env file usage

### ISSUE THREAD

**Issue by daSkier** [vapor/docs#464]
Are there any existing notes for .env usage in vapor4? I was looking for info in the docs and couldn't find anything. 

If it's helpful, I can contribute my notes from setting it up, but I'm not sure I'd cover the whole scope of the feature.

**Comment by grundoon** [comment]
The `dotenv` documentation currently in progress can be found in this commit: https://github.com/vapor/docs/pull/462/commits/9c20fa46f195f2d9cafb3e8f322fcfbc80777845

**Comment by daSkier** [comment]
Looks like this is coming with #462

**Comment by tanner0101** [comment]
https://docs.vapor.codes/4.0/environment/#env-dotenv
