### ISSUE TITLE
Discrepancy between implementation and Documentation about CatchAll "*"

### ISSUE THREAD

**Issue by Yourney** [vapor/docs#487]
The documentation states that CatchAll is handled by a ```"*"``` component in the PathComponents. However, the implementation of the ```"*"``` does not CatchAll.
The implementation of ```"**"``` does.

### Steps to reproduce

    app.get(["manager", "*"], use: controller.report)

This does not catch all, it only catches /manager/a, but not  /manager/a/b.

From the docs at https://docs.vapor.codes/4.0/routing/
I read:
```
Catchall

This is a dynamic route component that matches one or more components. It is specified using just *. Any string at this position or later positions will be allowed in the request.

// responds to GET /foo/bar
// responds to GET /foo/bar/baz
// ...
app.get("foo", "*") { req in 
    ...
}
```
That does not correspond to my test outcome.

### Expected behavior

I expect the Documentation to match the implementation. I suspect the documentation is wrong, cos when using "**", I do get catch all behaviour.

### Actual behavior

This does not catch all, it only catches /manager/a, but not  /manager/a/b.

I believe this is an omission in the documentation.
Using .catchall does work, and looking in the implementation of that .catchall, I see:
```
    /// A dynamic parameter component with discarded value.
    ///
    /// Represented as `*`
    case anything
    
    /// A fallback component that will match one *or more* dynamic
    /// parameter components with discarded values.
    ///
    /// Catch alls have the lowest precedence, and will only be matched
    /// if no more specific path components are found.
    ///
    /// Represented as `**`
    case catchall
```
Which indicates that the catch all is a double asterix.

### Environment
Vapor on Mac
xcode Version 11.4 (11E146)

* vapor/router version:
Vapor 4.4.0
Routing-kit 4.0.1

* OS version:
macOS 10.15.4 (19E287)

**Comment by tanner0101** [comment]
Looks like this was changed in https://github.com/vapor/routing-kit/releases/tag/4.0.0-beta.2 and never updated in the docs. Fixed now, thanks!
