### ISSUE TITLE
Auth -> Sessions example should use Basic auth

### ISSUE THREAD

**Issue by tanner0101** [vapor/docs#536]
The current auth sessions docs show setting up sessions + a bearer token: https://docs.vapor.codes/4.0/authentication/#session

This doesn't make a whole lot of sense since usually sessions are paired with a single login route. Showing basic auth, credential auth, or manual auth would make more sense here. 

This requires two routes groups looking like:

```swift
// Routes that use sessions
let sessions = admin.grouped([
    app.sessions.middleware,
    User.sessionAuthenticator(),
])
sessions.post("/login") { req in 
    // Some stuff
    req.auth.login(theUser)
}

// Routes that require login
let protected = sessions.grouped([
    User.redirectMiddleware(path: "/admin/login")
])
protected.get("/me") { req in 
    try req.auth.require(User.self)
}
```

**Comment by Lloople** [comment]
Login forms would be great too, i.e:

- Example of a basic login form
- Retrieving and login the user
  - redirecting to a dashboard if success
  - redirecting back with input errors if failed
