### ISSUE TITLE
Please add documentation related to how one can I add SSL to their vapor app (vapor 4)

### ISSUE THREAD

**Issue by pradeepb28** [vapor/docs#625]
**Is your feature request related to a problem? Please describe.**
I'm having hard time how one can I add SSL to their vapor app. I currently downloaded .crt from DO Managed db unfortunately, DO points out to refer your vapor app for installation but I couldn't find documentation related to it.

**Describe the solution you'd like**
It'd be great if their a section dedidcated how to install SSL in general as well as if it is specific servers like DO, please do describe it. 

**Describe alternatives you've considered**
There are no alternative right now, other than reaching out to community for help.

**Comment by 0xTim** [comment]
Do you mean add TLS so you can do `https://www.myapp.com` or work with a DB that is using a self-signed certificate?

**Comment by pradeepb28** [comment]
Yes TLS for "https" either will be using self-signed crt or letsencrypt

**Comment by 0xTim** [comment]
You can see details for how to configure that here https://docs.vapor.codes/4.0/server/#tls
