### ISSUE TITLE
Questions about Vapor documentation

### ISSUE THREAD

**Issue by CainLuo** [vapor/docs#633]
I am reading the Chinese version of the Vapor documentation, and I found some differences with the English version of the Vapor documentation, there are some contents that are not in the English version, but there are many more in the Chinese version, which one is the standard, please? The following figure shows:

English version:
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/8857291/149379079-ed834ff9-9385-4e4b-97f3-19af9356905c.png">

Chinese version:
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/8857291/149379219-6dc58d82-7b46-490e-9da8-a148a28fb6dd.png">

**Comment by 0xTim** [comment]
The English ones (this repo) is the source of truth. I'm not sure what's happened but looks like the Chinese one is out of sync. The missing parts are at https://docs.vapor.codes/4.0/fluent/model/#timestamp

**Comment by CainLuo** [comment]
> The English ones (this repo) is the source of truth. I'm not sure what's happened but looks like the Chinese one is out of sync. The missing parts are at https://docs.vapor.codes/4.0/fluent/model/#timestamp

A closer look reveals that it is the English version that is missing and not as much content as the Chinese one, which makes people wonder.

**Comment by 0xTim** [comment]
What is the English version missing? From what I can see it's just been expanded and moved

**Comment by CainLuo** [comment]
> What is the English version missing? From what I can see it's just been expanded and moved

There are no Sibilings and no Tiestamps in the English version of the Relationships chapter, is this moved to another chapter?

**Comment by 0xTim** [comment]
Siblings - https://docs.vapor.codes/4.0/fluent/relations/#siblings

Timestamp - https://docs.vapor.codes/4.0/fluent/model/#timestamp

There's a search field at the top you can use to find any content

**Comment by 0xTim** [comment]
Closing this as we've moved the Chinese docs to the main site now and everything is in sync. If you go to https://docs.vapor.codes there's a new icon in the nav bar to change the language
