### ISSUE TITLE
Leaf Highlight syntax is out of date

### ISSUE THREAD

**Issue by 0xTim** [vapor/docs#637]
Currently built for Leaf 3, we should add support for Leaf 4

https://github.com/highlightjs/highlight.js/blob/main/src/languages/leaf.js needs updating to current spec

**Comment by dannflor** [comment]
https://github.com/highlightjs/highlight.js/pull/3794/files

**Comment by dannflor** [comment]
Closed by https://github.com/highlightjs/highlight.js/pull/3794

**Comment by 0xTim** [comment]
Reopening this until we've pulled this into the docs site

**Comment by 0xTim** [comment]
Cc @ptoffy

**Comment by dannflor** [comment]
Hightlightjs finally bundled a new release with my changes. You should be able to get the next syntax with just an `npm update`
