### ISSUE TITLE
Autocreate translation issues

### ISSUE THREAD

**Issue by 0xTim** [vapor/docs#665]
We should create a GH action that runs whenever a PR is merged to create an issue for translating the documentation issues in that PR. The issue body should contain a link to the PR so we can link them up. This ensures that the translations don't get out of sync.

Even better if we can add a later to the PR to say `no-doc-update` required so it doesn't create issues with that label, for instance if we're changing the MKDocs layout, CI or a translation itself.

**Comment by mattesmohr** [comment]
That's a good idea. Pity I don't nothing about GH Actions. 

Till then, I found the CC (like the last time @0xTim ) helpful.
