### ISSUE TITLE
Create local Docker dev environment

### ISSUE THREAD

**Issue by 0xTim** [vapor/docs#680]
As we grow the docs site, customise it more and build more with more contributors, it would be good to have a Dockerfile that would build and run the docs mounting the repo so changes updated automatically. This would ensure that everyone has a consistent environment to use without needing the correct version of Python installed, setting up pip etc

We should then add it to the README to help people use it

**Comment by ahmednreldin** [comment]
Hello 0xTim, 
i've created a PR with the mentioned requirement
waiting your feedback
