### ISSUE TITLE
Documentation on custom site search with translations

### ISSUE THREAD

**Issue by scmcca** [vapor/docs#695]
On https://docs.vapor.codes/ it appears that the site search will only show results in the site's default language (English). 

It looks like something was done in the background using [fixSearchIndex.swift](https://github.com/vapor/docs/blob/main/fixSearchIndex.swift) to accomplish this (given that the mkdocs-material search bar and the i18n plugin don't always play well together).  

I wish to accomplish something similar on my site (search only in default English) and was wondering if you could document this workflow for others to benefit as well? 

Thanks!

**Comment by 0xTim** [comment]
The Swift script is what you're looking for. It basically loops through the generated search index and removes all the other languages

**Comment by 0xTim** [comment]
You can see the build process [here](https://github.com/vapor/docs/blob/main/.github/workflows/deploy.yml)

We build it with `mkdocs build`, run the scripts then copy the output to S3

**Comment by 0xTim** [comment]
So our CI pipeline (we use Github actions) looks like
* when a build is triggered, run `mkdocs build` to generate the HTML docs
* run the scripts to fix the search index and various other things like old redirects, analytics etc
* use a GitHub action to push the generated HTML and related files to S3. Under the hood this uses the AWS CLI to push the files to S3

We then use S3 as the web server (fronted by a CDN).


It sounds like you're using an MKDocs command to build and deploy to GH pages, so you'll need to move away from that, build the docs using the build command, fix the search index and then push the generated content to GH pages. Does that make sense?

**Comment by fredericsimard** [comment]
Yes, makes sense. What I'm missing is how the scripts are run. Swift isn't supported by GitHub actions now is it? At least I haven't found how to make it work. So we need a server somewhere with Vapor installed to have this build work?

**Comment by 0xTim** [comment]
Swift is available on the default GH Action runner so we can just execute our Swift script in that environment. There's no Vapor involved

**Comment by 0xTim** [comment]
(You can see that at https://github.com/vapor/docs/blob/main/.github/workflows/deploy.yml#L19)

**Comment by fredericsimard** [comment]
> Swift is available on the default GH Action runner so we can just execute our Swift script in that environment. There's no Vapor involved

That's awesome! I didn't know that. Well that will save a lot of trouble. Thank you so much!
