### ISSUE TITLE
DigitalOcean deploy docs dangerously outdated

### ISSUE THREAD

**Issue by gwynne** [vapor/docs#764]
The existing DO deployment documentation (http://docs.vapor.codes/deploy/digital-ocean/) is absurdly out of date and does not work as written.

**Comment by beastboym** [comment]
I would like to work but i'm a first timer.
Could you put me through on the details so I could know what to do?

**Comment by 0xTim** [comment]
@beastboym looks like you've been beaten to it unfortunately! However you can see our contributing guide here https://docs.vapor.codes/contributing/contributing/
